# Generated by Django 2.2 on 2019-04-21 04:15

from django.db import migrations


def create_group(apps, schema_editor):
    group = apps.get_model('users_groups', 'Group')
    group(name='Group_001', description='Description_001').save()


class Migration(migrations.Migration):

    dependencies = [
        ('users_groups', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_group)
    ]
