# Generated by Django 2.2 on 2019-04-21 04:41

from django.db import migrations


def create_user(apps, schema_editor):
    user = apps.get_model('users_groups', 'User')
    group = apps.get_model('users_groups', 'Group')
    group_1 = group.objects.all()
    user(username='User_001', group=group_1[0]).save()


class Migration(migrations.Migration):

    dependencies = [
        ('users_groups', '0002_users_groups'),
    ]

    operations = [
        migrations.RunPython(create_user)
    ]
