# Generated by Django 2.2 on 2019-04-21 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users_groups', '0004_auto_20190421_0600'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.CharField(max_length=255, verbose_name='description'),
        ),
    ]
